from PyQt5.QtWidgets import QWidget, QLabel, QPushButton, QLineEdit, QGridLayout

grit = QGridLayout()
win_edit = QWidget()
win_edit.resize(600,500)
win_edit.move(300,300)#

lbl_qw_edit = QLabel("Введіть запитання")
edit_qw = QLineEdit()
lbl_ans_edit = QLabel("Введіть вірну відповідь")
edit_ans = QLineEdit()
lbl_wrg1_edit = QLabel("Введіть першу хибну відповідь")
edit_wrg1 = QLineEdit()
lbl_wrg2_edit = QLabel("Введіть другу хибну відповідь")
edit_wrg2 = QLineEdit()
lbl_wrg3_edit = QLabel("Введіть третю хибну відповідь")
edit_wrg3 = QLineEdit()
btn_add_qw = QPushButton("Додати запитання")
btn_clear = QPushButton("Очистити")
lbl_stat = QLabel("Статистика")
lbl_count= QLabel("Разів відповіли")
lbl_count_right= QLabel("Вірних відповідей")
lbl_good = QLabel("Успішність")
btn_back = QPushButton("Назад")


grit.addWidget(lbl_qw_edit, 0, 0)
grit.addWidget(edit_qw, 0, 1)
grit.addWidget(lbl_ans_edit, 1, 0)
grit.addWidget(edit_ans, 1, 1)
grit.addWidget(lbl_wrg1_edit, 2, 0)
grit.addWidget(edit_wrg1, 2, 0)
grit.addWidget(lbl_wrg2_edit, 3, 0)
grit.addWidget(edit_wrg2, 3, 1)
grit.addWidget(lbl_wrg3_edit, 4, 0)
grit.addWidget(edit_wrg3, 4, 1)
grit.addWidget(btn_add_qw, 5, 0)
grit.addWidget(btn_clear, 5, 1)
grit.addWidget(lbl_stat, 6, 0)
grit.addWidget(lbl_count, 7, 0)
grit.addWidget(lbl_count_right, 8, 0)
grit.addWidget(lbl_good, 9, 0)
grit.addWidget(btn_back, 10, 1)
